   148.4ms (setup:858): 2024-06-18 01:40:06
   148.5ms (setup:859): /usr/bin/pipx install ta-lib
   148.5ms (setup:860): pipx version is 1.4.3
   148.6ms (setup:861): Default python interpreter is '/usr/bin/python3'
   148.6ms (mkdir:74): creating directory /root/.local/share/pipx/venvs
   148.9ms (mkdir:74): creating directory /root/.local/bin
   149.0ms (mkdir:74): creating directory /root/.local/share/man
   149.1ms (mkdir:74): creating directory /root/.cache/pipx
   149.3ms (setup:870): Adding CACHEDIR.TAG to cache directory
   150.4ms (package_name_from_spec:370): Determined package name: ta-lib
   150.5ms (package_name_from_spec:371): Package name determined in 0.0s
   151.2ms (run_subprocess:168): running /usr/bin/python3 -m venv --without-pip /root/.local/share/pipx/venvs/ta-lib
   222.0ms (run_subprocess:190): stdout:
   222.1ms (run_subprocess:192): stderr:
   222.2ms (run_subprocess:193): returncode: 0
   222.8ms (run_subprocess:168): running /usr/bin/python3 -m venv --clear /root/.local/share/pipx/shared
  3884.7ms (run_subprocess:190): stdout:
  3884.8ms (run_subprocess:192): stderr:
  3884.9ms (run_subprocess:193): returncode: 0
  3885.2ms (run_subprocess:168): running <checking pip's availability>
  3912.9ms (run_subprocess:190): stdout: ModuleSpec(name='pip', loader=<_frozen_importlib_external.SourceFileLoader object at 0x7eba977fffb0>, origin='/root/.local/share/pipx/shared/lib/python3.12/site-packages/pip/__init__.py', submodule_search_locations=['/root/.local/share/pipx/shared/lib/python3.12/site-packages/pip'])
  3913.0ms (run_subprocess:193): returncode: 0
  3913.2ms (upgrade:98): Upgrading shared libraries in /root/.local/share/pipx/shared
  3913.7ms (run_subprocess:168): running /root/.local/share/pipx/shared/bin/python -m pip --no-input --disable-pip-version-check install --force-reinstall -q --upgrade pip >= 23.1
  6304.7ms (run_subprocess:190): stdout:
  6304.8ms (run_subprocess:192): stderr:
  6304.8ms (run_subprocess:193): returncode: 0
  6305.1ms (run_subprocess:168): running /root/.local/share/pipx/venvs/ta-lib/bin/python -c import sysconfig; print(sysconfig.get_path('purelib'))
  6329.7ms (run_subprocess:190): stdout: /root/.local/share/pipx/venvs/ta-lib/lib/python3.12/site-packages
  6329.8ms (run_subprocess:193): returncode: 0
  6330.0ms (run_subprocess:168): running /root/.local/share/pipx/shared/bin/python -c import sysconfig; print(sysconfig.get_path('purelib'))
  6351.7ms (run_subprocess:190): stdout: /root/.local/share/pipx/shared/lib/python3.12/site-packages
  6351.8ms (run_subprocess:193): returncode: 0
  6352.1ms (run_subprocess:168): running /root/.local/share/pipx/venvs/ta-lib/bin/python --version
  6354.0ms (run_subprocess:190): stdout: Python 3.12.3
  6354.1ms (run_subprocess:192): stderr:
  6354.1ms (run_subprocess:193): returncode: 0
  6354.3ms (_parsed_package_to_package_or_url:137): cleaned package spec: ta-lib
  6354.7ms (run_subprocess:168): running /root/.local/share/pipx/venvs/ta-lib/bin/python -m pip --no-input install ta-lib
 98703.4ms (run_subprocess:193): returncode: 0
 98704.0ms (run_subprocess:168): running <fetch_info_in_venv commands>
 98732.7ms (run_subprocess:190): stdout: {"sys_path": ["/usr/lib/python312.zip", "/usr/lib/python3.12", "/usr/lib/python3.12/lib-dynload", "/root/.local/share/pipx/venvs/ta-lib/lib/python3.12/site-packages", "/root/.local/share/pipx/shared/lib/python3.12/site-packages"], "python_version": "3.12.3", "environment": {"implementation_name": "cpython", "implementation_version": "3.12.3", "os_name": "posix", "platform_machine": "x86_64", "platform_release": "6.8.0-35-generic", "platform_system": "Linux", "platform_version": "#35-Ubuntu SMP PREEMPT_DYNAMIC Mon May 20 15:51:52 UTC 2024", "python_full_version": "3.12.3", "platform_python_implementation": "CPython", "python_version": "3.12", "sys_platform": "linux"}}
 98732.8ms (run_subprocess:193): returncode: 0
 98780.0ms (get_venv_metadata_for_package:339): get_venv_metadata_for_package: 76ms
 98780.3ms (_parsed_package_to_package_or_url:137): cleaned package spec: ta-lib
 98780.7ms (rmdir:55): removing directory /root/.local/share/pipx/venvs/ta-lib
 98853.4ms (cli:924): PipxError: No apps associated with package ta-lib. Try again with '--include-deps' to include apps of dependent packages, which are listed above. If you are attempting to install a
library, pipx should not be used. Consider using pip or a similar tool instead.
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/pipx/main.py", line 921, in cli
    return run_pipx_command(parsed_pipx_args)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3/dist-packages/pipx/main.py", line 219, in run_pipx_command
    return commands.install(
           ^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3/dist-packages/pipx/commands/install.py", line 100, in install
    run_post_install_actions(
  File "/usr/lib/python3/dist-packages/pipx/commands/common.py", line 427, in run_post_install_actions
    raise PipxError(
pipx.util.PipxError: No apps associated with package ta-lib. Try again with '--include-deps' to include apps of dependent packages, which are listed above. If you are attempting to install a
library, pipx should not be used. Consider using pip or a similar tool instead.
 98854.4ms (cli:932): pipx finished.
